name: 'Testes Unitários Manuais'

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - uses: actions/checkout@v4

      # Instala o Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instala as dependências
      - name: Instalando dependências
        run: npm install

      # Executa os testes com Mocha
      - name: Executando testes unitários
        run: npx mocha
