name: 'Testes Unitários Agendados'

on:
  schedule:
    - cron: '0 6 * * 0' # Executa todo domingo às 06:00 UTC

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando dependências
        run: npm install

      - name: Executando testes unitários
        run: npx mocha ./testes/01-testes.js
